### ISSUE TITLE
Cilkscale on Ubuntu 18

### ISSUE THREAD

**Issue by dcurtisatmit** [OpenCilk/infrastructure#17]
Running cilkscale on qsort from tutorial.
Seems to work ok until trying to plot...

ubuntu@nms-data:~/opencilk/dcurtis/tutorial$ python3 /tmp/opencilk/share/Cilkscale_vis/cilkscale.py -c ./qsort_wsp -b ./qsort_wsp_bench --args 10000000
Namespace(args=['10000000'], cilkscale='./qsort_wsp', cilkscale_benchmark='./qsort_wsp_bench', cpu_counts=None, output_csv='out.csv', output_plot='plot.pdf', rows_to_plot='all')

>> STDOUT (./qsort_wsp 10000000)
Sorting 10000000 integers
All sorts succeeded
<< END STDOUT

>> STDERR (./qsort_wsp 10000000)
<< END STDERR

INFO:runner:Generating scalability data for 2 cpus.
INFO:runner:CILK_NWORKERS=1 taskset -c 0 ./qsort_wsp_bench 10000000
INFO:runner:CILK_NWORKERS=2 taskset -c 0,1 ./qsort_wsp_bench 10000000
INFO:plotter:Generating plot
/tmp/opencilk/share/Cilkscale_vis/plotter.py:130: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "/tmp/opencilk/share/Cilkscale_vis/cilkscale.py", line 5, in <module>
    from plotter import plot, can_plot
  File "/tmp/opencilk/share/Cilkscale_vis/plotter.py", line 8, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 72, in <module>
    from matplotlib.backends import pylab_setup
  File "/usr/lib/python3/dist-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()

  matplotlib.use('PDF')
Traceback (most recent call last):
  File "/tmp/opencilk/share/Cilkscale_vis/cilkscale.py", line 49, in <module>
    main()
  File "/tmp/opencilk/share/Cilkscale_vis/cilkscale.py", line 46, in main
    plot(out_csv, out_plot, rows_to_plot, cpus)
  File "/tmp/opencilk/share/Cilkscale_vis/plotter.py", line 131, in plot
    fig, axs = plt.subplots(nrows=num_plots, ncols=2, figsize=(12,6*num_plots), squeeze=False)
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 1176, in subplots
    fig = figure(**fig_kw)
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 539, in figure
    **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 171, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_tkagg.py", line 1049, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by DorothyCurtis** [comment]
Seems to work fine on V2RC2.  Thanks!

**Comment by neboat** [comment]
Thanks for investigating this issue.  Since everything seems to be working now with the latest version of OpenCilk, I'm closing this issue.

**Comment by DorothyCurtis** [comment]
I'm in agreement with closing this issue!

Dorothy
